version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/backend"
      - "/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(npm):"